version: '3.7'

services:
  server:
    image: urbinek/fake-5g-controlx:latest
    
    networks:
      - overlay
    
    ports:
      - "8888:80/tcp"
    
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    
    stdin_open: true
    tty: true

networks:
  overlay:

